config/routes.rb
Rails.application.routes.draw do

  # Some setup you must do manually if you haven't yet:

  #   Ensure you have overridden routes for generated controllers in your routes.rb.
  #   For example:

  #     Rails.application.routes.draw do
  #       devise_for :users, controllers: {
  #         sessions: 'users/sessions'
  #       }
  #     end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    resources :skills, only: [:index, :new, :create]
  end

  resources :skills, only: [:destroy]

  root to: 'pages#home'

  resources :application_requests, only: [:index]

  resources :projects, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :application_requests, only: [:new, :create]
    resources :roles, only: [:new, :create]
    resources :suggestions, only: [:index, :new, :create]
    resources :suggestion_votes, only: [:create]

  end

  resources :collaborators, only: [:destroy]

  resources :application_requests, only: [:destroy]

  resources :roles, only: [:destroy, :update, :edit]

  resources :chatrooms, only: {} do
    resources :messages, only: :create
  end

  # resources :photos, path_names: { new: 'make', edit: 'change' }

  get "my_projects", to: "projects#my_projects", as: "my_projects"
  get "my_project_request", to: "application_requests#my_project_request"

  get "application_requests/:application_request_id/chatroom", to: "chatrooms#chatroom", as: "application_request_chatroom"

  put "application_requests/:application_id/accept", to: "application_requests#accept", as: "accept"
  put "application_requests/:application_id/decline", to: "application_requests#decline", as: "decline"

  get "about", to: "pages#about", as: "about"

end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :technology
  belongs_to :level
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!

  def index
    @skills = policy_scope(Skill)
    @skill = Skill.new
    @techs = Technology.all
    @levels = Level.all
    @user = current_user
  end

  def new
    @techs = Technology.all
    @levels = Level.all
    @skill = Skill.new
    @user = current_user
    authorize @skill
  end

  def create
    @user = current_user
    @skill = current_user.skills.new(skill_params)
    authorize @skill
    if @skill.save
      redirect_to user_skills_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    authorize @skill
    @user = current_user
    @skill.destroy
    redirect_to user_skills_path(current_user)
  end

  private

  def skill_params
    params.require(:skill).permit(:technology_id, :level_id)
  end


end

app/views/skills/_index.html.erb
<div class="container">
  <h2>Mis skills</h2>

  <div class="">
    <% @skills.each do |skill| %>
      <div>
        <p><%= skill.technology.name %> <%= skill.level.name %></p>
      </div>
    <% end %>

    <p><%= link_to "Add skill", new_user_skill_path %></p>



  </div>


</div>

app/views/skills/index.html.erb
<div class="container">
  <h2> Mis skills 🏅</h2>
    <div>
      <div class="row">
        <% @skills.each do |skill| %>
          <div class="skill-card col-xs-12 col-sm-4 col-sm-offset-4">
            <div class="skill-content">
              <%= sanitize pick_tech_icon(skill.technology.name), tags: %w(i), attributes: %w(class style) %>
              <p class="skill-title"><strong><%= skill.technology.name %></strong> - <%= skill.level.name.capitalize %></p>
              <p><%= link_to "Eliminar", skill_path(skill), method: :delete, data: { confirm: 'Eliminar skill?'}, class: "fas fa-trash-alt px-3 orange", class: "btn btn-warning" %></p>
            </div>
          </div>
        <% end %>
        <div class="skill-card col-xs-12 col-sm-4 col-sm-offset-4">
          <div class="skill-content add-skill-card">
            <h5>Agregar Skill</h5>
            <%= simple_form_for [ @user, @skill ] do |f| %>
            <p>Seleccionar tecnología</p>
              <%= f.collection_select :technology_id, @techs, :id, :name%>
            <p>Seleccionar nivel</p>
              <%= f.collection_select :level_id, @levels, :id, :name%>
              <br>
              <%= f.submit "Agregar", class: "btn btn-primary skill-submit-btn mt-4" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>


<style>
  .skill-card {
    text-align: center;
    margin-bottom: 50px;
    padding-right: 10px;
    padding-left: 10px;
    height: 100%;
  }
  .skill-title {
    border-top: 1px solid black;
    border-bottom: 1px solid black;
    width: 200px;
    margin: auto;
    margin-bottom: 25px;
  }

  .skill-content {
    border: 1px solid white;
    background-color: white;
    border-radius: 16px;
    text-align: center;
    margin-right: 25px;
    margin-left: 25px;
    box-shadow: 2px 2px 12px rgba(0,0,0,0.3);
  }

  .add-skill-card {
    height: 260px;
  }
  .add-skill-card p {
    margin-top: 22px;
    margin-bottom: 0px;
  }

  h2 {
    margin-top: 25px;
    margin-bottom: 50px;

  }

  .add-skill-card h5 {
    margin-top: 10px;
    margin-bottom: 5px;
    width: 184px;
    border-bottom: 1px solid black;
    /* text-align: center; */
    margin-left: auto;
    margin-right: auto
  }


  body > div.container > div > div > div > div > i {
    font-size: 130px;
    margin-top: 8px;
    margin-bottom: 15px;
  }
</style>

app/views/skills/new.html.erb
<!-- https://medium.com/@theresamorelli/collection-select-what-the-heck-4e1cabc4be4b -->


<div class="container">
  <h2> Mis skills 🏅</h2>
  <div class="row">
    <div class="skill-card col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="skill-content add-skill-card">
        <h5>Agregar Skill</h5>
        <%= simple_form_for [ @user, @skill ] do |f| %>
        <p>Seleccionar tecnología</p>
          <%= f.collection_select :technology_id, @techs, :id, :name%>
        <p>Seleccionar nivel</p>
          <%= f.collection_select :level_id, @levels, :id, :name%>
          <br>
          <%= f.submit "Agregar", class: "btn btn-primary skill-submit-btn mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<style>
  .skill-card {
    text-align: center;
    margin-bottom: 50px;
    padding-right: 10px;
    padding-left: 10px;
    height: 100%;
  }
  .skill-title {
    border-top: 1px solid black;
    border-bottom: 1px solid black;
    width: 200px;
    margin: auto;
    margin-bottom: 25px;
  }

  .skill-content {
    border: 1px solid white;
    background-color: white;
    border-radius: 16px;
    text-align: center;
    margin-right: 25px;
    margin-left: 25px;
    box-shadow: 2px 2px 12px rgba(0,0,0,0.3);
  }

  .add-skill-card {
    height: 260px;
  }
  .add-skill-card p {
    margin-top: 22px;
    margin-bottom: 0px;
  }

  h2 {
    margin-top: 25px;
    margin-bottom: 50px;

  }

  .add-skill-card h5 {
    margin-top: 10px;
    margin-bottom: 5px;
    width: 184px;
    border-bottom: 1px solid black;
    /* text-align: center; */
    margin-left: auto;
    margin-right: auto
  }


  body > div.container > div > div > div > div > i {
    font-size: 130px;
    margin-top: 8px;
    margin-bottom: 15px;
  }
</style>