config/routes.rb
Rails.application.routes.draw do

  # Some setup you must do manually if you haven't yet:

  #   Ensure you have overridden routes for generated controllers in your routes.rb.
  #   For example:

  #     Rails.application.routes.draw do
  #       devise_for :users, controllers: {
  #         sessions: 'users/sessions'
  #       }
  #     end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    resources :skills, only: [:index, :new, :create]
  end

  resources :skills, only: [:destroy]

  root to: 'pages#home'

  resources :application_requests, only: [:index]

  resources :projects, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :application_requests, only: [:new, :create]
    resources :roles, only: [:new, :create]
    resources :suggestions, only: [:index, :new, :create]
    resources :suggestion_votes, only: [:create]

  end

  resources :collaborators, only: [:destroy]

  resources :application_requests, only: [:destroy]

  resources :roles, only: [:destroy, :update, :edit]

  resources :chatrooms, only: {} do
    resources :messages, only: :create
  end

  # resources :photos, path_names: { new: 'make', edit: 'change' }

  get "my_projects", to: "projects#my_projects", as: "my_projects"
  get "my_project_request", to: "application_requests#my_project_request"

  get "application_requests/:application_request_id/chatroom", to: "chatrooms#chatroom", as: "application_request_chatroom"

  put "application_requests/:application_id/accept", to: "application_requests#accept", as: "accept"
  put "application_requests/:application_id/decline", to: "application_requests#decline", as: "decline"

  get "about", to: "pages#about", as: "about"

end

app/views/shared/_add_skill_modal.html.erb
<% if user_signed_in? %>
  <div id="skillsModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Te gustaria agregar un skill a tu perfil?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <p class="mr-3 mb-0" style="font-size: 1.4rem; text-align: center;">
               <%= link_to (sanitize pick_tech_icon(Technology.first.name), tags: %w(i), attributes: %w(class style)) %>
               <%= link_to (sanitize pick_tech_icon(Technology.second.name), tags: %w(i), attributes: %w(class style)) %>
               <%= link_to (sanitize pick_tech_icon(Technology.third.name), tags: %w(i), attributes: %w(class style)) %>
               <%= link_to (sanitize pick_tech_icon(Technology.fourth.name), tags: %w(i), attributes: %w(class style)) %>
               <%= link_to (sanitize pick_tech_icon(Technology.fifth.name), tags: %w(i), attributes: %w(class style)) %>
            </p>
          <p>Los skills te van a permitir aplicar a proyectos y filtrar aquellos a los que puedes aplicar segun sus requerimientos</p>
        </div>
        <div class="modal-footer">
          <%= link_to "Agregar mi primer skill", new_user_skill_path(current_user), class:"btn btn-primary" %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Más tarde</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_applications_show.html.erb
<div class="container">
  <h2 class="tab-title">Aplicaciones de usuarios</h2>
  <% @project.application_requests.each do |application| %>
    <%= render "application_requests/application_request_partial", application: application %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" class="d-block d-md-flex">
  <div class="footer-links my-2">
    <%= link_to "Acerca de Nosotros", about_path %>
  </div>
  <div><p style="color: white">Copyright TeamAppsis 2020</p></div>
  <div class="footer-copyright my-2">
    TeamAppsis fue hecha con <i class="fa fa-heart mx-1" aria-hidden="true" style="color: #D23333;"></i> en LeWagon Batch #384
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon fixed-top">
  <div class="d-flex">
  <% if user_signed_in? %>
    <%= link_to projects_path, class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "logo.png" %>
      <p class="mb-0 ml-1 navbar-logo-text">TeamAppsis</p>
    <% end %>
  <% else %>
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "logo.png" %>
      <p class="mb-0 ml-1 navbar-logo-text">TeamAppsis</p>
    <% end %>
  <% end %>
      <%= form_tag projects_path, method: :get, class: "d-none d-sm-flex flex-nowrap mt-3" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control mb-3 navbar-search",
          placeholder: "Busca proyectos..."%>
        <%= button_tag type: 'submit', class: "search-button" do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "Mis Proyectos", my_projects_path, class: "nav-link" %>
        </li>

        <!-- notificación simple si hay candidatos pendientes -->
        <% if (current_user.projects.any? {|project| project.application_requests.any? {|app_request| app_request.status == "pending"}})  %>
          <li class="nav-item">
            <%= link_to "Mis Candidatos", my_project_request_path, class: "nav-link" %>
            <span class="notification-dot"></span>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Mis Candidatos", my_project_request_path, class: "nav-link text-muted" %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "Mis Aplicaciones", application_requests_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
           <%= link_to "Crear Proyecto", new_project_path, class: "d-block nav-link d-md-none" %>
        </li>
        <li class="btn p-0 nav-item dropdown ml-2">
          <%= avatar_fixer(current_user, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false)  %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mis skills", user_skills_path(current_user), class: "dropdown-item text-muted" %>
            <%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item text-muted" %>
            <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "dropdown-item text-muted" %>
          </div>
        </li>
        <div class="nav-link ml-2" >
          <% if current_user.first_name.nil? %>
            Hola <%= current_user.email.split('@').first.capitalize %>
          <% else  %>
            Hola <%= current_user.first_name %>
          <% end %>
        </div>
      <% else %>
        <li class="nav-item d-flex">
          <%= link_to "Crear cuenta", new_user_registration_path, class: "nav-link"  %>
          <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="navbar-invisible-div"></div>

app/views/shared/_roles_show_new.html.erb
<div class="container">
  <h2 class="tab-title">Roles del proyecto</h2>
  <div class="card-wrapper">
    <% @project.roles.each do |role| %>
      <div class="card-role">
        <div class="card-body text-center">
          <h5 class="card-title mb-3"><%= role.name %></h5>
          <!-- logica avatars/mensaje si el role esta ocupado o vacante -->
          <!-- si esta ocupado -->
          <% if !role.open? %>

            <% if role == @project.roles[0] %>
              <%= avatar_fixer(@project.collaborators.first.user, data: { toggle: 'tooltip' }, class: "avatar-bordered mx-2", title: "#{@project.collaborators.first.user.first_name} / #{@project.collaborators.first.role.name} [Fundador]") %>
              <p class="role-status my-3 red-salsa">Esta posición está ocupada</p>
            <% else %>
              <%= avatar_fixer(role.active_collaborator.user, data: { toggle: 'tooltip' }, class: "avatar dropdown-toggle", title: "#{role.active_collaborator.user.first_name} / #{role.name}") %>
              <p class="role-status my-3 red-salsa">Esta posición está ocupada</p>
              <!-- si esta vacante -->
            <% end %>
          <% else %>
            <%= image_tag "/assets/default-user-img.png", class: "avatar" %>
            <p class="role-status my-3 forest-green">Esta posición está vacante</p>
          <% end %>
          <div class="skill-level d-flex justify-content-center">
            <% role.requirements.each do |requirement| %>
              <div class="d-flex text-center icons-wrapper">
                <p class="mr-2" data-toggle="tooltip" title="<%= requirement.technology.name %> - <%= requirement.level.name.capitalize %>">
                  <%= sanitize pick_tech_icon(requirement.technology.name), tags: %w(i), attributes: %w(class style) %>
                </p>
              </div>
            <% end %>
          </div>
          <div>
            <h6 class="mb-0 mt-3"> Funciones del puesto </h6>
            <p class="card-text"><%= role.description %></p>
              <div class="edit-delete-role text-center d-flex">
                <p><%= link_to "", edit_role_path(role), data: { toggle: 'tooltip' }, title: "Editar Rol", class:"fas fa-edit mr-2", style:"text-decoration: none;"%> </p>
                <% if !role.open? %>
                  <p><%= link_to "", collaborator_path(role.active_collaborator), method: :delete, data: { toggle: 'tooltip', confirm: 'Estas seguro de eliminar a este colaborador?' }, title: "Eliminar Colaborador", class:"fas fa-trash mr-2" %></p>
                <% else %>
                  <p><%= link_to "", role_path(role), data: { toggle: 'tooltip', confirm: "¿Estás seguro?" }, method: :delete, title: "Borrar Rol", class:"fas fa-trash mr-2", style:"text-decoration: none;" %> </p>
                <% end %>
              </div>
          </div>

        </div>
      </div>
      <% end %>

      <div id="new-role-form" class="card-role mb-3">
        <div class="card-body text-center">
          <h5 class="card-title">Nuevo rol</h5>
          <div class="container">

            <%= simple_form_for([ @project, @role ], remote: true) do |f| %>
              <%= simple_fields_for :requirement do |ff| %>
                <%= ff.input :technology_id, collection: Technology.all, label:false, prompt: "Tecnología" %>
                <%= ff.input :level_id, collection: Level.all, label:false, prompt: "Nivel" %>
              <% end %>

              <%= f.input :name, label:false, placeholder: "Nombre del rol" %>
              <%= f.input :description, label:false, placeholder: "Descripción" %>
              <%= f.submit "Enviar", class: "btn btn-primary" %>
            <% end %>

          </div>
        </div>
      </div>
  </div>
</div>