config/routes.rb
Rails.application.routes.draw do

  # Some setup you must do manually if you haven't yet:

  #   Ensure you have overridden routes for generated controllers in your routes.rb.
  #   For example:

  #     Rails.application.routes.draw do
  #       devise_for :users, controllers: {
  #         sessions: 'users/sessions'
  #       }
  #     end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    resources :skills, only: [:index, :new, :create]
  end

  resources :skills, only: [:destroy]

  root to: 'pages#home'

  resources :application_requests, only: [:index]

  resources :projects, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :application_requests, only: [:new, :create]
    resources :roles, only: [:new, :create]
    resources :suggestions, only: [:index, :new, :create]
    resources :suggestion_votes, only: [:create]

  end

  resources :collaborators, only: [:destroy]

  resources :application_requests, only: [:destroy]

  resources :roles, only: [:destroy, :update, :edit]

  resources :chatrooms, only: {} do
    resources :messages, only: :create
  end

  # resources :photos, path_names: { new: 'make', edit: 'change' }

  get "my_projects", to: "projects#my_projects", as: "my_projects"
  get "my_project_request", to: "application_requests#my_project_request"

  get "application_requests/:application_request_id/chatroom", to: "chatrooms#chatroom", as: "application_request_chatroom"

  put "application_requests/:application_id/accept", to: "application_requests#accept", as: "accept"
  put "application_requests/:application_id/decline", to: "application_requests#decline", as: "decline"

  get "about", to: "pages#about", as: "about"

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :roles, dependent: :destroy
  has_many :requirements, through: :roles
  has_many :technologies, through: :requirements
  has_many :collaborators, through: :roles
  has_many :suggestions
  has_many :application_requests, through: :roles
  has_many :chatrooms, through: :application_requests
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { in: 6..500 }
  validate :photo_present
  validate :links_with_httpwww_removed

  # scope :with_open, -> { joins(:roles).merge(Role.vacant) }
  # scope :open_roles, -> { left_outer_joins(:collaborators).where(role: { collaborator_id: nil })}

  #filtro
  def self.with_open_positions
    @projects = []
    Project.all.each do |project|
      @projects << project if project.roles.count { |role| role.open? } > 0
    end
    return @projects
  end

  def self.that_match_my_skills(current_user)
    user = current_user
    @projects = with_open_positions
    @matches = []
    @projects.each do |project|
      @matches << project if project.technologies.any? { |project_tech| user.technologies.any? { |user_tech| user_tech == project_tech } }
    end
    return @matches
  end

  def self.that_match_single_skill(skill_name)
    @projects = with_open_positions
    @matches = []
    @projects.each do |project|
      @matches << project if project.technologies.any? { |project_tech| skill_name == project_tech.name }
    end
    return @matches
  end

  def photo_present
    unless photo.attached?
      photo.attach(io: File.open(Dir.getwd + "/app/assets/images/new hardcode logo.png"), filename: "project-default.png", content_type: 'image/png')
    end
  end


  def links_with_httpwww_removed
    regex = %r{^(?:https?:\/\/)?(?:www\.)?}i
    unless link_1.nil?
      link_1.match?(regex) ? link_1.gsub!(regex, '') : link_1
    end
    unless link_2.nil?
      link_2.match?(regex) ? link_2.gsub!(regex, '') : link_2
    end
  end

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:name],
    associated_against: {
      roles: [:name],
      technologies: [:name]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :destroy, :edit, :update]
  skip_before_action :authenticate_user!, only: [:index]

  def index

    if user_signed_in?
      @user = current_user
    end
    if params[:query].present?
        sql_query = " \
        projects.name @@ :query \
        OR roles.name @@ :query \
        OR technologies.name @@ :query \
       "

      @projects = policy_scope(Project).joins(:roles, :technologies).where(sql_query, query: "%#{params[:query]}%").uniq
    else
      @projects = policy_scope(Project.order(:id))
    end

    #filtros
    if params[:with_open_roles]
      @projects = Project.with_open_positions
    elsif params[:skill_match]
      @projects = Project.that_match_my_skills(current_user)
    elsif params[:single_skill_match]
      @projects = Project.that_match_single_skill(params[:skill_name])
    end

  end


  def new
    @project = Project.new
    @role = Role.new
    authorize @project
    authorize @role
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @role = Role.new(role_params)
    @role.project = @project
    authorize @project
    authorize @role
    if @role.save && @project.save
      # los skills de un rol no son propios del role sino que estan asociados a un requirement
      @requirement = Requirement.new(requirement_params)
      authorize @requirement
      @requirement.role = @role
      @requirement.save


      @collaborator = Collaborator.new(status: "active")
      @collaborator.role = @role
      @collaborator.user = current_user
      @collaborator.save!
      redirect_to project_path(@project)
    else
      render :new
    end
  end


  def edit; end

  def update
    @project.update(project_params)
    if @project.save
      redirect_to @project
    else
      render :edit
    end
  end


  def destroy
    @project.destroy
    redirect_to projects_path
  end

  def show
    authorize @project
    @project_roles = @project.roles
    @role = Role.new
    authorize @role
    @suggestion = Suggestion.new
    authorize @suggestion
    @vote = SuggestionVote.new
    authorize @vote
  end

  def my_projects
    @projects = current_user.projects
    authorize @projects
  end

  private

  def collaborators_counter
    @colaborator_count = Project.collaborators.count
  end

  def project_params
    params.require(:project).permit(:name, :description, :photo, :link_1, :link_2)
  end

  def role_params
    params.require(:role).permit(:name, :description, :technology_id, :level_id)
  end

  def set_project
    @project = Project.find(params[:id])
    authorize @project
  end

  def requirement_params
    params.require(:requirement).permit(:technology_id, :level_id)
  end

end

app/views/projects/_history_partial.html.erb
<% array = [] %>
<% project.application_requests.select { |application| application.status == "accepted" }.each do |application| %>
  <% array << application %>
<% end %>
<% project.suggestions.each do |suggestion| %>
  <% array << suggestion %>
<% end %>

<div class="px-3">
  <div class="d-flex justify-content-between align-items-center p-3 mt-3 border rounded shadow-blue-bg">
    <div>
      <div class="d-flex align-items-center position-relative">
        <%= avatar_fixer(project.user, class: "avatar mr-3") %>
        <i class="fas fa-rocket position-absolute new-project-icon d-flex justify-content-center align-items-center"></i>
        <div>
          <small class="mint-cream"><%= l(project.created_at.getlocal, format: :long) %></small>
          <p class="mb-1"><strong><%= project.user.first_name %></strong> inició el proyecto como <%= project.roles.first.name %></p>
        </div>
      </div>
    </div>
  </div>
  <% array.sort { |a, b| a.created_at <=> b.created_at }.each do |element| %>
    <% if element.class == ApplicationRequest %>
      <div class="d-flex justify-content-between align-items-center p-3 mt-3 border rounded shadow-blue-bg">
        <div>
          <div class="d-flex align-items-center position-relative">
            <%= avatar_fixer(element.user, class: "avatar mr-3") %>
            <i class="fas fa-user-check position-absolute new-collaborator-icon d-flex justify-content-center align-items-center"></i>
            <div>
              <small class="mint-cream"><%= l(element.created_at.getlocal, format: :long) %></small>
              <p class="mb-1"><strong><%= element.user.first_name %></strong> se unió como <%= element.role.name %></p>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="d-flex justify-content-between align-items-center p-3 mt-3 border rounded shadow-blue-bg">
        <div class="d-flex align-items-center position-relative">
          <%= avatar_fixer(element.collaborator.user, class: "avatar mr-3") %>
          <i class="fas fa-lightbulb position-absolute new-suggestion-icon d-flex justify-content-center align-items-center"></i>
          <div>
            <small class="mint-cream"><%= l(element.created_at.getlocal, format: :long) %></small>
            <p class="mb-1"><strong><%= element.collaborator.user.first_name %></strong> hizo una sugerencia: <%= element.description %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/projects/_index-card.html.erb
<% path = project.user == current_user || project.collaborators.any? { |collaborator| collaborator.user == current_user } ?  project_url(project) : new_project_application_request_url(project) %>
<div class="index-project-card index-project-card-clickable border rounded" data-target-url="<%= path %>">
  <div class="d-flex">
    <%= cl_image_tag project.photo.key, alt: "alttext", width: 300, height: 300, crop: :fill, class: "project-card-logo mr-3 ml-2 rounded" %>
    <div>
      <h2 class="text-left"><%= project.name %></h2>
      <p class="text-muted"><%= project.description %></p>
    </div>
    <% if project.sponsored %>
      <div class="badge badge-pill badge-warning project-card-sponsored d-flex justify-content-between">
        <i class="fa fa-heart" aria-hidden="true" style="color: #da64ab;"></i>
        <div class="d-none d-sm-block d-md-block d-lg-block d-xl-block ml-1">Sponsoreado</div>
      </div>
    <% end %>
  </div>
  <div class="d-lg-flex d-block">
    <div class="d-flex flex-column justify-content-between w-100 w-lg-50 mr-3">
      <h3>Links</h3>
      <div>
        <% if project.link_1 != nil && project.link_1 != "" %>
          <%= link_to "http://#{project.link_1}", class: "link-z-index" do %>
            <div class="d-flex align-items-center mb-2">
              <%= sanitize pick_url_icon(project.link_1) %>
              <div class="d-inline ml-1">
                <%= truncate(shorten_url(project.link_1), length: 30)  %>
              </div>
            </div>
          <% end %>
        <% end %>
        <% if project.link_2 != nil && project.link_2 != "" %>
          <%= link_to "http://#{project.link_2}", class: "link-z-index" do %>
            <div class="d-flex align-items-center mb-2">
              <%= sanitize pick_url_icon(project.link_2) %>
              <div class="d-inline ml-1">
                <%= truncate(shorten_url(project.link_2), length: 30) %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <% if project.roles.count { |role| role.open? } == 0  %>
      <div class="no-positions rounded mb-2 mb-lg-0">
        <p>Este proyecto está cubierto <i class="fas fa-heart-broken ml-1"></i></p>
      </div>
      <% else %>
      <div class="open-positions rounded mb-2 mb-lg-0">
        <p><%= pluralize(project.roles.count { |role| role.open? }, "posición abierta", plural: "posiciones abiertas") %></p>
      </div>
      <% end %>
    </div>

    <div class="w-100 w-lg-50">
      <div>
        <h3>Tags</h3>
        <div class="d-flex flex-wrap icons-wrapper">
          <% project.technologies.uniq.take(10).each do |technology| %>
            <p class="mr-3 mb-2" data-toggle="tooltip" title="<%= technology.name %>">
              <%= sanitize pick_tech_icon(technology.name), tags: %w(i), attributes: %w(class style) %>
            </p>
          <% end %>
        </div>
      </div>

      <div>
        <h3>Colaboradores <span class="badge badge-pill badge-light"><%= project.collaborators.count { |x| x.status = "active" } %></span></h3>
          <% project.collaborators.each do |collaborator| %>
            <%= avatar_fixer(collaborator.user, class: "avatar-small mr-2", data: { toggle: 'tooltip' }, title: "#{collaborator.user.first_name} / #{collaborator.role.name}") %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_my_feed_partial.html.erb
<div class="my-feed pb-3">
  <div class="d-flex align-items-center justify-content-center my-feed-header rounded-top shadow-blue-bg mb-3">
    <strong class="ml-2">Mi Feed</strong>
  </div>
  <h6 style="text-align: center;">Filtrar proyectos</h6>
  <div class="px-3">
    <p><%= link_to "Con posiciones abiertas", projects_path(:with_open_roles => "true"), class:"btn btn-success btn-sm" %></p>
    <% if user_signed_in? %>
      <p><%= link_to "Que coinciden con mis skills", projects_path(:skill_match => "true"), class:"btn btn-success btn-sm" %></p>
      <h6 style="text-align: center;">Según uno de mis skills</h6>
      <% if current_user.technologies.empty? %>
        <p class="mb-0 text-muted">No tienes skills cargados :(</p>
        <p><%= link_to "Agregá skills", new_user_skill_path(current_user) %> </p>
      <% else %>
        <div class="d-flex justify-content-center flex-wrap">
          <% current_user.technologies.each do |technology| %>
            <p class="mr-3 mb-0" style="font-size: 1.4rem" data-toggle="tooltip" title="<%= technology.name %>">
               <%= link_to (sanitize pick_tech_icon(technology.name), tags: %w(i), attributes: %w(class style)), projects_path(:single_skill_match => "true", :skill_name => technology.name) %>
            </p>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/_my_profile_partial.html.erb
<% if user_signed_in? %>
  <div class="my-profile pb-3 mb-3">
    <div class="d-flex align-items-center justify-content-center my-feed-header rounded-top shadow-blue-bg mb-3">
      <strong class="ml-2">Mi Perfil</strong>
    </div>
      <%= avatar_fixer(current_user, class: "avatar-large mb-2") %>
    <h6 style="text-align: center;"><strong><%= current_user.first_name %> <%= current_user.last_name %></strong></h6>
    <p class="mx-2 text-muted"><%= truncate(current_user.description, length: 150) %></p>
    <%= link_to "Crear Proyecto", new_project_path, class:"btn btn-success" %>
  </div>
<% end %>

app/views/projects/_new_edit_form.html.erb
<div class="container mt-4">
  <div class=>
    <div class="form-group">
      <!-- project -->
      <%= simple_form_for(@project, remote: true) do |f| %>
      <%= f.error_notification %>
      <%= f.input :name, label: "Nombre", placeholder: "Nombre del Proyecto" %>
      <%= f.input :description, as: :text, placeholder: "Describe tu proyecto", label: "Descripción" %>
      <%= f.input :link_1, as: :text, placeholder: "Agrega links a tu proyecto! (GitHub, LinkedIn, website...)" %>
      <%= f.input :link_2, as: :text, placeholder: "Agrega links a tu proyecto! (GitHub, LinkedIn, website...)" %>
      <%= f.input :photo, as: :file, label: "Adjunta un logo" %>
      <!-- role -->
      <%= simple_fields_for @role do |r| %>
      <%= r.label "Crea tu rol dentro del proyecto" %>
      <%= r.input :name, placeholder: "Nombre de tu rol", label: "Nombre del rol" %>
      <%= r.input :description, placeholder: "Descripción de tu rol", label: "Descripción" %>

      <!-- requirement -->
      <%= simple_fields_for :requirement do |ff| %>
      <%= ff.input :technology_id, collection: Technology.all, label:false, prompt: "Tecnología" %>
      <%= ff.input :level_id, collection: Level.all, label:false, prompt: "Nivel" %>
      <% end %>
      <% end %>
      <%= f.button :submit, "Aceptar", class: "btn-primary" %>
      <%= f.button :button, "Cancelar", type: "reset", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class='container'>
  <%= render 'new_edit_form' %>
</div>

app/views/projects/index.html.erb
<%= render "shared/add_skill_modal" %>


<div class="container mt-3">
  <div class="grid-index-container mt-3">
    <div class="floating-sidebar">
      <%= render "projects/my_profile_partial" %>
      <%= render "projects/my_feed_partial" %>
    </div>
    <div class="d-flex align-items-center justify-content-center logo-concat">
      <%= image_tag "logo.png", class: "index-logo" %>
      <div class="ml-1">
        <p class="mb-0 logo-text">TeamAppsis</p>
        <p class="mb-0">Buscando soluciones a problemas reales</p>
      </div>
    </div>
    <div class="index-projects">
      <% @projects.each do |project| %>
        <%= render "projects/index-card", project: project %>
      <% end %>
    </div>
  </div>
</div>

<div id="user-skills" style="display: none;">
  <% if @user %>
    <%= @user.skills.count %>
  <% end %>
</div>

app/views/projects/my_projects.html.erb
<div class="container">
  <h3>Mis Proyectos</h3>
  <% if @projects == [] %>
  <h5> Todavía no creaste ningún Proyecto 🚀 </h5>
  <%= link_to "Crear Proyecto", new_project_path, class: "btn-sm btn btn-success mb-3 btn-lg" %>
  <% else %>
    <% @projects.each do |project| %>
    <div class="index-project-card border rounded">
    <div class="d-flex">
    <%= cl_image_tag project.photo.key, alt: "alttext", width: 100, height: 100, crop: :fill%>
    <div class="ml-2">
      <h2 class="text-left"><%= project.name %></h2>
      <p class="text-muted"><%= project.description %></p>
    </div>
    </div>
       <div class="d-lg-flex justify-content-between w-100 w-lg-50 mr-5 mt-2">
          <div class="d-flex flex-column justify-content-between w-100 w-lg-50 mr-5">
            <h5>Links</h5>
            <div>
              <% if project.link_1 != nil && project.link_1 != "" %>
                <%= link_to "http://#{project.link_1}", class: "link-z-index" do %>
                  <div class="d-flex align-items-center mb-2">
                    <%= sanitize pick_url_icon(project.link_1) %>
                    <div class="d-inline ml-1">
                      <%= truncate(shorten_url(project.link_1), length: 30)  %>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <% if project.link_2 != nil && project.link_2 != "" %>
                <%= link_to "http://#{project.link_2}", class: "link-z-index" do %>
                  <div class="d-flex align-items-center mb-2">
                    <%= sanitize pick_url_icon(project.link_2) %>
                    <div class="d-inline ml-1">
                      <%= truncate(shorten_url(project.link_2), length: 30) %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
            <% if project.roles.count { |role| role.open? } == 0  %>
            <div class="no-positions mb-2 mb-lg-0">
              <p>Todas las posiciones de tu proyecto estan cubiertas <i class="ml-1"></i></p>
            </div>
            <% else %>
            <div class="open-positions mb-2 mb-lg-0">
              <p><%= pluralize(project.roles.count { |role| role.open? }, "posición por cubrir", plural: "posiciones por cubrir") %></p>
            </div>
            <% end %>
          </div>

          <div class="w-100 w-lg-50">
            <div>
              <h5>Tags</h5>
              <div class="d-flex flex-wrap icons-wrapper">
                <% project.technologies.uniq.take(10).each do |technology| %>
                  <p class="mr-3 mb-2" data-toggle="tooltip" title="<%= technology.name %>">
                    <%= sanitize pick_tech_icon(technology.name), tags: %w(i), attributes: %w(class style) %>
                  </p>
                <% end %>
              </div>
            </div>

            <div class="mt-2">
              <h5>Colaboradores <span class="badge badge-pill badge-light"><%= project.collaborators.count { |x| x.status = "active" } %></span></h5>
                <% project.collaborators.each do |collaborator| %>
                  <%= avatar_fixer(collaborator.user, class: "avatar-small mr-2", data: { toggle: 'tooltip' }, title: "#{collaborator.user.first_name} / #{collaborator.role.name}") %>
                <% end %>
            </div>
          </div>
          <div class="mr-5 icons-wrapper">
            <p><%= link_to "", project_path(project), data: { toggle: 'tooltip' }, title: "Ver Proyecto", class:"fas fa-project-diagram", style:"text-decoration: none;"%></p>
            <p><%= link_to "", new_project_role_path(project), data: { toggle: 'tooltip' }, title: "Crear nuevo Rol", class:"fas fa-folder-plus", style:"text-decoration: none;"%></p>
            <p><%= link_to "", edit_project_path(project), data: { toggle: 'tooltip' }, title: "Editar Proyecto", class:"fas fa-edit mr-1", style:"text-decoration: none;"%></p>
            <p><%= link_to "", project_path(project), data: { toggle: 'tooltip', confirm: "¿Estás seguro?" }, method: :delete, title: "Eliminar Proyecto", class:"fas fa-trash", style:"text-decoration: none;"  %></p>
          </div>
        </div>
      </div>

  <% end %>
  </div>
<% end %>
</div>

app/views/projects/new.html.erb
<div class='container'>
  <%= render 'new_edit_form' %>
</div>

app/views/projects/show.html.erb
<div class='project-container mr-5'>
  <div class='project-overview mx-3'>
    <% if @project.photo.attached? %>
    <%= cl_image_tag @project.photo.key, alt: "alttext", crop: :fill,  class:"project-image" %>
    <% else %>
    <%= image_tag "project-default", class:"project-image" %>
    <% end %>
    <h4 class='text-center mt-3'> <%= @project.name %></h4>
    <div class="tech-images">
      <% @project.technologies.uniq.each do |technology| %>
      <p class="ml-3 mb-0 icons-wrapper" data-toggle="tooltip" title="<%= technology.name %>">
        <%= sanitize pick_tech_icon(technology.name), tags: %w(i), attributes: %w(class style) %>
      </p>
      <% end %>
    </div>
    <div class="project-collaborators text-center">
      <div class="description-container">
        <h5> Descripción </h5>
        <div class="project-description">
          <p class="mx-3"><%= @project.description %></p>
        </div>
      </div>
      <div class="project-collaborators text-center">
        <h5>Colaboradores</h5>
        <div>
          <%= avatar_fixer(@project.collaborators.first.user, data: { toggle: 'tooltip' }, class: "avatar-bordered mx-2", title: "#{@project.collaborators.first.user.first_name} / #{@project.collaborators.first.role.name} [Fundador]") %>
          <% @project.collaborators.drop(1).each do |collaborator| %>
            <%= avatar_fixer(collaborator.user, data: { toggle: 'tooltip' }, class: "avatar mx-2", title: "#{collaborator.user.first_name} / #{collaborator.role.name}") %>
          <% end %>
        </div>
      </div>
      <div class="links">
        <% if @project.link_1 != nil && @project.link_1 != "" %>
          <h5>Links</h5>
          <p><a href="http://<%= @project.link_1 %>", class="text-decoration-none"><%= sanitize pick_url_icon(@project.link_1) %> <%= shorten_url(@project.link_1) %></a></p>
        <% end %>
        <% if @project.link_2 != nil && @project.link_2 != "" %>
          <p><a href="http://<%= @project.link_2 %>", class="text-decoration-none"><%= sanitize pick_url_icon(@project.link_2) %> <%= shorten_url(@project.link_2) %></a></p>
        <% end %>
      </div>
    </div>
  </div>
    <div class="tabs-container border rounded" >
      <!-- Tabs https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior-->
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link <%= ["applications", nil].include?(params[:tab]) ? "active" : "" %> " id="applications-tab" data-toggle="tab" href="#applications" role="tab" aria-controls="applications" aria-selected="true">Aplicaciones</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= params[:tab] == "roles" ? "active" : "" %> " id="roles-tab" data-toggle="tab" href="#roles" role="tab" aria-controls="roles" aria-selected="false">Roles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= params[:tab] == "suggestions" ? "active" : "" %>" id="suggestions-tab" data-toggle="tab" href="#suggestions" role="tab" aria-controls="suggestions" aria-selected="false">Sugerencias</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= params[:tab] == "evolution" ? "active" : "" %>" id="evolution-tab" data-toggle="tab" href="#evolution" role="tab" aria-controls="evolution" aria-selected="false">Historial</a>
        </li>
      </ul>

      <!-- Tab content -->
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade <%= ["applications", nil].include?(params[:tab]) ? "show active" : "" %>" id="applications" role="tabpanel" aria-labelledby="home-tab">
          <%= render "shared/applications_show" %>
        </div>
        <div class="tab-pane fade  <%= params[:tab] == "roles" ? "show active" : "" %>" id="roles" role="tabpanel" aria-labelledby="roles-tab">
          <%= render "shared/roles_show_new" %>
        </div>
        <div class="<%= params[:tab] == "evolution" ? "show active" : "" %> tab-pane fade" id="evolution" role="tabpanel" aria-labelledby="evolution-tab">
          <%= render "history_partial", project: @project %>
        </div>
        <div class="<%= params[:tab] == "suggestions" ? "show active" : "" %> tab-pane fade" id="suggestions" role="tabpanel" aria-labelledby="suggestions-tab">
          <%= render "suggestions/index" %>
        </div>
      </div>
    </div>
</div>