config/routes.rb
Rails.application.routes.draw do

  # Some setup you must do manually if you haven't yet:

  #   Ensure you have overridden routes for generated controllers in your routes.rb.
  #   For example:

  #     Rails.application.routes.draw do
  #       devise_for :users, controllers: {
  #         sessions: 'users/sessions'
  #       }
  #     end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    resources :skills, only: [:index, :new, :create]
  end

  resources :skills, only: [:destroy]

  root to: 'pages#home'

  resources :application_requests, only: [:index]

  resources :projects, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :application_requests, only: [:new, :create]
    resources :roles, only: [:new, :create]
    resources :suggestions, only: [:index, :new, :create]
    resources :suggestion_votes, only: [:create]

  end

  resources :collaborators, only: [:destroy]

  resources :application_requests, only: [:destroy]

  resources :roles, only: [:destroy, :update, :edit]

  resources :chatrooms, only: {} do
    resources :messages, only: :create
  end

  # resources :photos, path_names: { new: 'make', edit: 'change' }

  get "my_projects", to: "projects#my_projects", as: "my_projects"
  get "my_project_request", to: "application_requests#my_project_request"

  get "application_requests/:application_request_id/chatroom", to: "chatrooms#chatroom", as: "application_request_chatroom"

  put "application_requests/:application_id/accept", to: "application_requests#accept", as: "accept"
  put "application_requests/:application_id/decline", to: "application_requests#decline", as: "decline"

  get "about", to: "pages#about", as: "about"

end

app/models/application_request.rb
class ApplicationRequest < ApplicationRecord
  after_commit :save_user_as_collaborator, on: [:update, :create]
  after_commit :create_chatroom, on: [:create]

  has_one_attached :file
  belongs_to :role
  has_one :project, through: :role
  has_one :chatroom, dependent: :destroy
  belongs_to :user
  validates :about_me, presence: true, length: { in: 10..300 }
  validates :status, inclusion: { in: ['pending', 'accepted', 'declined by user', 'declined by owner', 'pending response from applicant'] }
  def save_user_as_collaborator
    if status == "accepted"
      collaborator = Collaborator.new(role_id: role_id, user_id: user_id, status: "active")
      collaborator.save!
    end
  end

  def create_chatroom
    @chatroom = Chatroom.new(name: "Aplicación de #{user.first_name} #{user.last_name} para el puesto de #{role.name}")
    @chatroom.application_request = self
    @chatroom.save!
  end

  def technologies
    technologies = []
    self.role.requirements.each do |requirement|
      technologies << requirement.technology.name
    end
    return technologies
  end
end

app/controllers/application_requests_controller.rb
class ApplicationRequestsController < ApplicationController
  before_action :authenticate_user!
  skip_after_action :verify_authorized, only: [:my_project_request]
  def index
    @applications = policy_scope(ApplicationRequest)
  end

  def new
    @project = Project.find(params[:project_id])
    @application = ApplicationRequest.new
    authorize @application
  end

  def create
    @application = ApplicationRequest.new(application_params)
    authorize @application
    @application.user = current_user
    role = Role.find(params[:role_id])
    @application.role = role
    if @application.save
      redirect_to application_requests_path
    else
      # definir @project si se usa render, sino el view no encuentra @project y crashea
      @project = Project.find(params[:project_id])
      render :new
    end
  end

  def my_project_request
    @projects = current_user.projects
  end

  def accept
    @application = ApplicationRequest.find(params[:application_id])
    @project = @application.project
    authorize @application

    if current_user == @application.user
      @application.update(status: "accepted")
      redirect_to application_requests_path(:anchor => @application.id)
    else
      @application.update(status: "pending response from applicant")
      redirect_to project_path(@project, tab: "applications")
    end
  end

  def decline
    @application = ApplicationRequest.find(params[:application_id])
    @project = @application.project
    authorize @application
    if current_user == @application.user
      @application.update(status: "declined by user")
     redirect_to application_requests_path(:anchor => @application.id)
    else
      @application.update(status: "declined by owner")
      redirect_to project_path(@project, tab: "applications")
    end
  end

  def destroy
    @application = ApplicationRequest.find(params[:id])
    authorize @application
    @application.destroy
    redirect_to application_requests_path
  end

  private

  def application_params
    params.require(:application_request).permit(:about_me, :file)
  end
end

app/views/application_requests/_application_request_partial.html.erb
<div class="card-request p-3 my-3">
  <div class="d-flex m-2 justify-content-between">
    <div class="d-flex flex-column justify-content-between mx-2 w-50">
      <h5> Rol: <%= application.role.name  %></h5>
      <p class="text-muted mb-1"> <%= application.role.description %> </p>
      <p class="mb-0"> Requisitos para el puesto:</p>
      <div class="d-flex flex-wrap mb-2">
        <% application.role.requirements.each do |requirement|%>
          <div class="mr-2 mb-1" data-toggle="tooltip" title="<%= requirement.technology.name %> - <%= requirement.level.name.capitalize %>">
            <%= sanitize pick_tech_icon(requirement.technology.name), tags: %w(i), attributes: %w(class style) %>
          </div>
        <% end %>
      </div>
      <div>
        <%= render "application_requests/my_project_request_case", application: application %>
      </div>
    </div>
    <div class="d-flex flex-column justify-content-between ml-3 w-50">
      <h5 class="mt-3"> Información del candidato</h5>
      <div class="d-flex">
        <div>
          <%= avatar_fixer(application.user, class: "avatar mr-2", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
        </div>
        <p class="ml-2 mt-2"> <strong><%= application.user.first_name %> <%= application.user.last_name %></strong>  </p>
      </div>
      <p class="mb-0"> Acerca del candidato: <%= application.about_me %></p>
      <div class="d-flex flex-column my-0">
        <p class="mb-0" style="font-weight: bolder;">Skills 🏅</p>
        <div class="applicant-skills d-flex">
          <% application.user.skills.each do |skill| %>
          <p data-toggle="tooltip" title="<%= skill.technology.name %> - <%= skill.level.name.capitalize %>" class="mx-1"><%= sanitize pick_tech_icon(skill.technology.name), tags: %w(i), attributes: %w(class style) %></p>
          <% end %>

        </div>

      </div>

      <div>
        <button type="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#staticBackdrop_<%= application.id  %>">
          Ver adjunto del candidato
        </button>
        <%= render "application_requests/modal_file", application: application %>
        <% if current_user == application.project.user && (application.status == "pending" || application.status == "pending response from applicant" || application.status == "accepted") %>
          <%= link_to "Contacta al candidato", application_request_chatroom_path(application.id), class: "btn btn-warning mb-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/application_requests/_index_case.html.erb
<% case application.status.downcase %>
<% when "pending response from applicant" %>
<div>
  <p class="honey-yellow mb-2" style="font-weight: bolder">Tu aplicación ha sido aceptada por <%= application.project.name %> y están esperando tu respuesta</p>
  <div>
    <%= link_to "Aceptar", accept_path(application), method: :put, class:"btn btn-success mb-3 mr-1", remote: true %>
    <%= link_to "Declinar", decline_path(application), method: :put, class:"btn btn-danger mb-3", remote: true %>
  </div>
</div>
<% when "declined by owner" %>
<p class="mb-0 red-salsa" style="font-weight: bolder">Tu aplicación ha sido declinada</p>
<% end %>
<% case application.status.downcase %>
<% when "pending" %>
<p class="mb-0 honey-yellow" style="font-weight: bolder"> Pendiente</p>
<% when "accepted" %>
<p class="mb-0" style="color:green; font-weight: bolder"> ¡Felicitaciones! Ahora formas parte del equipo de <%= application.project.name %></p>
<% when "declined by user" %>
<p class="mb-0 red-salsa" style="font-weight: bolder"> Has declinado la invitación de <%= application.project.name %></p>
<% end %>

app/views/application_requests/_modal_file.html.erb
<div class="modal fade" id="staticBackdrop_<%= application.id  %>" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-body">
        <div>
          <% if application.file.attached? %>
            <%= cl_image_tag(application.file.key, format: :jpg) %>
          <% else %>
            <p>El solicitante no subió ningun archivo</p>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/application_requests/_modal_window.html.erb
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div>
        <%= project.name %>
      </div>
      <div>
        <%= project.description %>
      </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-primary">Aplicar</button>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
    </div>
    </div>
  </div>
</div>

app/views/application_requests/_my_project_request_case.html.erb
<% case application.status %>
<% when "pending" %>
  <div>
    <p class="honey-yellow mb-2" style="font-weight: bolder">El candidato está esperando respuesta de <%= application.project.user.first_name %></p>
    <% if current_user == application.project.user %>
      <div>
        <%= link_to "Aceptar", accept_path(application), method: :put, class:"btn btn-success mb-3 mr-1", remote: true %>
        <%= link_to "Declinar", decline_path(application), method: :put, class:"btn btn-danger mb-3", remote: true %>
      </div>
    <% end %>
  </div>
<% when "pending response from applicant" %>
  <p class="honey-yellow" style="font-weight: bolder">La aplicación de <%= application.user.first_name %> fue aceptada y está pendiente de respuesta del candidato</p>
<% when "declined by owner" %>
  <p class="red-salsa" style="font-weight: bolder">Has declinado la aplicación de <%= application.user.first_name %></p>
<% when "accepted" %>
  <p style="color: green; font-weight: bolder">¡El candidato ha aceptado y forma parte del equipo!</p>
<% when "declined by user" %>
  <p class="red-salsa" style="font-weight: bolder">El candidato ha declinado</p>
<% end %>

app/views/application_requests/index.html.erb
<div class="container my-2">
  <h2 class="my-3">Proyectos a los que aplicaste</h2>
    <% if @applications.any? %>

      <% @applications.order("created_at DESC").each do |application| %>
      <div class="index-application-card border rounded" id="<%= application.id %>">
        <div class="d-flex">
          <%= cl_image_tag application.project.photo.key, alt: "alttext", width: 300, height: 300, crop: :fill, class: "project-card-logo mr-3 ml-2 rounded" %>
          <div>
            <h2 class="text-left"><%= application.project.name %></h2>
            <p class="text-muted"><%= application.project.description %></p>
          </div>
          <% if application.project.sponsored %>
          <div class="badge badge-pill badge-warning project-card-sponsored d-flex justify-content-between">
            <i class="fa fa-heart" aria-hidden="true" style="color: #da64ab;"></i>
            <div class="d-none d-sm-block d-md-block d-lg-block d-xl-block ml-1">Sponsoreado</div>
          </div>
          <% end %>
        </div>
        <div class="d-flex justify-content-between">
          <div class="d-flex flex-column pr-3">
            <h4 class="h5 m-0 flex-grow-0 mb-2">Rol aplicado</h4>
            <div class="flex-grow-1 mb-2">
              <%= application.role.name %>
            </div>
            <h4 class="h6 m-0 flex-grow-0 mb-2">Estado</h4>
            <div class="flex-grow-1">
              <%= render "application_requests/index_case", application: application %>
            </div>
          </div>
          <div class="d-flex flex-column pl-3 w-50">
            <h4 class="h5 flex-grow-0 mb-3">Tags</h4>
            <div class="d-flex icons-wrapper mb-3">
              <% application.role.requirements.each do |requirement| %>
              <p class="mr-2 mb-0" data-toggle="tooltip" title="<%= requirement.technology.name %>">
               <%= sanitize pick_tech_icon(requirement.technology.name), tags: %w(i), attributes: %w(class style) %>
             </p>
             <% end %>
           </div>
           <h3 class="mb-3">Colaboradores <span class="badge badge-pill badge-light"><%= application.project.collaborators.count { |x| x.status = "active" } %></span></h3>
           <div class="align-items-center">
            <% if application.status == "accepted" %>
            <%= link_to "Link del Proyecto", application.project, class: "btn btn-primary mb-3"%>
            <% end %>
            <% if application.status == "pending" || application.status == "pending response from applicant" || application.status == "accepted" %>
            <%= link_to "Contacta al project owner", application_request_chatroom_path(application.id),  class: "btn btn-sm btn-primary mb-3"  %>
            <%= link_to "Retirar aplicación", application_request_path(application), method: :delete, data: { confirm: "Estas seguro? El Project Owner dejará de ver tu aplicación" }, class:"btn btn-sm btn-danger mb-3"  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% else %>
    <p>No tienes aplicaciones aún :(</p>
    <% end %>
    </div>
  </div>
</div>

app/views/application_requests/my_project_request.html.erb
<div class="container my-2">
  <h2>Mis solicitudes</h2>
  <% if @projects.select { |project| project.application_requests.count > 0 } == 0 %>
    <p>No tienes solicitudes aún :(</p>
  <% else %>
    <% @projects.select { |project| project.application_requests.count > 0 }.each do |project| %>
      <h3 class="ml-2">Candidatos a <%= project.name %> </h3>
        <% project.application_requests.each do |application| %>
            <%= render "application_requests/application_request_partial", application: application %>
        <% end %>
    <% end %>
  <% end %>
</div>

app/views/application_requests/new.html.erb
<div class='container mt-5'>
  <h1 class='text-center'>Estás aplicando a <%= @project.name %></h1>
  <h6 class='text-center'>Estas son las posiciones disponibles en este proyecto</h6>
   <div class='application-request-container mt-5'>
      <div class='grid-solicitudes'>
        <div class='card-project'>
          <div>
            <% if @project.photo.attached? %>
            <%= cl_image_tag @project.photo.key, alt: "alttext", crop: :fill,  class:"project-image" %>
            <% else %>
            <%= image_tag "project-default", class:"project-image" %>
            <% end %>
            <h5 class='text-center'>Información sobre el proyecto</h5>
              <div class="mx-4">
                <div>
                  <p class="text-justify"><%= @project.description %></p>
                </div>
                  <div>
                    <div>
                    </div>
                    <h5 class="ml-0">Colaboradores</h5>
                    <div class="">
                      <% @project.collaborators.each do |collaborator| %>
                        <%= avatar_fixer(collaborator.user, data: { toggle: 'tooltip' }, class: "avatar ml-2", title: "#{collaborator.user.first_name} / #{collaborator.role.name}") %>
                      <% end %>
                    </div>
                  </div>
            </div>
          </div>
        </div>

        <div  class="container form-apply mb-3">
         <div class="card-roles mt-3">
            <% @project.roles.each do |role| %>
              <% if role.open? %>
                <div class="card clickable-card" data-target="<%= role.id %>" data-delete="<%= role.id %>">
                  <div class="card-body text-center">
                    <h5 class="card-title"><%= role.name %></h5>
                     <% role.requirements.each do |requirement|%>
                     <div class="d-flex flex-wrap m-0 icons-wrapper">
                      <p class=" text-left mr-2 mb-0" data-toggle="tooltip" title="<%= requirement.technology.name %>">
                        <%= sanitize pick_tech_icon(requirement.technology.name), tags: %w(i), attributes: %w(class style) %>
                      </p>
                      <p class='mb-0'><%= requirement.level.name %></p>
                     </div>
                      <% end %>
                    <p class="card-text mt-4"><%= role.description %></p>
                    <% if role.application_requests.any? { |application| application.user != current_user } || role.application_requests.empty? %>
                      <button class="btn btn-primary"> <i class="fas fa-plus-circle primary mr-1"></i>Aplicar</button>
                    <% else %>
                      <div class="text-muted position-absolute mb-3 fixed-bottom">¡Ya aplicaste a este rol!</div>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <% end %>
          </div>

          <% if @project.roles.count { |role| role.open? } == 0  %>
          <div class="no-positions rounded mb-2 mb-lg-0">
            <p>Este proyecto está cubierto <i class="fas fa-heart-broken ml-1"></i></p>
          </div>
          <% else %>
            <%= simple_form_for [@project, @application] do |f| %>
            <input type="" hidden="true" name='role_id' value="role" class="role_field">
            <div class='file-container text-light mt-4 '>
              <h5>Sube tu CV</h5>
              <%= f.input :file, label: "Adjuntar archivo pdf", as: :file %>
            </div>
            <div class="text-light mb-4 text-left">
              <div class=" text-left">
                <%= f.input :about_me, placeholder: "Cuéntanos por qué deberíamos sumarte al equipo :)", label: "Acerca de mí" %>
                <%= f.submit "Enviar solicitud", class: "btn btn-primary"%>
              </div>
            </div>
          <% end %>
        <% end %>
        </div>
      </div>
  </div>
</div>